name: CI
on: [workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: run one line script
        run: echo Hello World 
  test: 
    runs-on: Ubuntu-latest
    needs: build
    steps:
     - name: Test 
       run: echo Hello World!
